execution_env=local
#execution_env=remote

appURL1=https://localhost/opencart/upload
appURL2=https://tutorialsninja.com/demo/
email=nkumar01#@gmail.com
password=ne#a9hwKHUALCV
#password=ne#a9hwKHUALCV..
searchProductName=iPhone